source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NHRecorder_Example', :exclusive => true do
  pod "NHRecorder", :path => "../"
end

target 'NHRecorder_Tests', :exclusive => true do
  pod "NHRecorder", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
